# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

allele_tracing_cpp <- function(sire_hap, dam_hap, cross_hap, chr_pos, block_pos, Father_cross_ped, Mother_cross_ped, Unknow_cross_ped, sire_hap_ind, dam_hap_ind, cross_hap_ind, hap_win = 50L, cpu_cores = 1L) {
    .Call(`_cBar2_allele_tracing_cpp`, sire_hap, dam_hap, cross_hap, chr_pos, block_pos, Father_cross_ped, Mother_cross_ped, Unknow_cross_ped, sire_hap_ind, dam_hap_ind, cross_hap_ind, hap_win, cpu_cores)
}

makeA_partial_cpp <- function(Pedigree, IND_name, record_pos, full_rank) {
    .Call(`_cBar2_makeA_partial_cpp`, Pedigree, IND_name, record_pos, full_rank)
}

makeAinv_partial_cpp <- function(Pedigree, IND_name, record_pos, full_rank) {
    .Call(`_cBar2_makeAinv_partial_cpp`, Pedigree, IND_name, record_pos, full_rank)
}

G_matrix_partial_cpp <- function(cross_hap, cross_boa, sire_hap, dam_hap) {
    .Call(`_cBar2_G_matrix_partial_cpp`, cross_hap, cross_boa, sire_hap, dam_hap)
}

makeHA_partial_cpp <- function(P_A, G_A, n_pure, n_cross, IND_geno, pos_A11, pos_A22, pos_geno, pos_A, pos_H22, direct = FALSE, inverse = TRUE, omega = 0.05) {
    .Call(`_cBar2_makeHA_partial_cpp`, P_A, G_A, n_pure, n_cross, IND_geno, pos_A11, pos_A22, pos_geno, pos_A, pos_H22, direct, inverse, omega)
}

makeAinv_old_partial_cpp <- function(Pedigree, IND_name, record_pos) {
    .Call(`_cBar2_makeAinv_old_partial_cpp`, Pedigree, IND_name, record_pos)
}

makeA_partial_cpp1 <- function(Pedigree) {
    .Call(`_cBar2_makeA_partial_cpp1`, Pedigree)
}

cumulativeSum <- function(input, result) {
    invisible(.Call(`_cBar2_cumulativeSum`, input, result))
}

paste_vec_short <- function(data) {
    .Call(`_cBar2_paste_vec_short`, data)
}

get_haplotype_set_short <- function(data_haplotype) {
    .Call(`_cBar2_get_haplotype_set_short`, data_haplotype)
}

allele_get_haplotype_set_short <- function(data_haplotype, haplotype_allele, i_pos) {
    invisible(.Call(`_cBar2_allele_get_haplotype_set_short`, data_haplotype, haplotype_allele, i_pos))
}

define_block_window_kb_cpp <- function(block1, block2, tmp_data_map_3) {
    .Call(`_cBar2_define_block_window_kb_cpp`, block1, block2, tmp_data_map_3)
}

single_base_factor_cpp <- function(data, miss_base) {
    .Call(`_cBar2_single_base_factor_cpp`, data, miss_base)
}

pair_base_factor_cpp <- function(data, miss_base) {
    .Call(`_cBar2_pair_base_factor_cpp`, data, miss_base)
}

get_blupf90_allele_string_phased_vcf <- function(allele_string_col1, allele_string_col2, max_length, cumsum_haplo_type_num, n_snp) {
    .Call(`_cBar2_get_blupf90_allele_string_phased_vcf`, allele_string_col1, allele_string_col2, max_length, cumsum_haplo_type_num, n_snp)
}

get_blupf90_allele_string_numeric <- function(allele_string_row, max_length) {
    .Call(`_cBar2_get_blupf90_allele_string_numeric`, allele_string_row, max_length)
}

make_bigmemory_object_cpp <- function(nrow, ncol, file_name, file_path, type) {
    .Call(`_cBar2_make_bigmemory_object_cpp`, nrow, ncol, file_name, file_path, type)
}

make_bigmemory_object_address_cpp <- function(nrow, ncol, file_name, file_path, type) {
    .Call(`_cBar2_make_bigmemory_object_address_cpp`, nrow, ncol, file_name, file_path, type)
}

NumericMatrix_to_arma <- function(data_numeric) {
    .Call(`_cBar2_NumericMatrix_to_arma`, data_numeric)
}

DataFrame_to_arma <- function(data_numeric) {
    .Call(`_cBar2_DataFrame_to_arma`, data_numeric)
}

get_offspring_generation_cpp <- function(ped, IND_base) {
    .Call(`_cBar2_get_offspring_generation_cpp`, ped, IND_base)
}

single_pedigree_cpp <- function(ped) {
    .Call(`_cBar2_single_pedigree_cpp`, ped)
}

get_blupf90_allele_string_unphased_haplotype <- function(allele_string_col1, allele_string_col2, max_length) {
    .Call(`_cBar2_get_blupf90_allele_string_unphased_haplotype`, allele_string_col1, allele_string_col2, max_length)
}

union_cpp <- function(X, Y) {
    .Call(`_cBar2_union_cpp`, X, Y)
}

delete_bigmemory_file_cpp <- function(matrix_type, bigmemory_data_name, bigmemory_data_path, message) {
    invisible(.Call(`_cBar2_delete_bigmemory_file_cpp`, matrix_type, bigmemory_data_name, bigmemory_data_path, message))
}

get_allele <- function(Pedigree) {
    .Call(`_cBar2_get_allele`, Pedigree)
}

matrix_col3_old <- function(G, IND_geno, det, cpu_cores, threshold) {
    .Call(`_cBar2_matrix_col3_old`, G, IND_geno, det, cpu_cores, threshold)
}

matrix_col3_memory_old <- function(pBigMat, bigmemory_data_name, bigmemory_data_path, IND_geno, det, cpu_cores, threshold) {
    .Call(`_cBar2_matrix_col3_memory_old`, pBigMat, bigmemory_data_name, bigmemory_data_path, IND_geno, det, cpu_cores, threshold)
}

matrix_col3_memory_alt <- function(G, bigmemory_data_name, bigmemory_data_path, IND_geno, det, cpu_cores, threshold) {
    .Call(`_cBar2_matrix_col3_memory_alt`, G, bigmemory_data_name, bigmemory_data_path, IND_geno, det, cpu_cores, threshold)
}

matrix_col3 <- function(G, IND_geno, det = FALSE, cpu_cores = 1L, threshold = 0) {
    .Call(`_cBar2_matrix_col3`, G, IND_geno, det, cpu_cores, threshold)
}

matrix_col3_memory <- function(pBigMat, bigmemory_data_name, bigmemory_data_path, IND_geno, det, cpu_cores, threshold) {
    .Call(`_cBar2_matrix_col3_memory`, pBigMat, bigmemory_data_name, bigmemory_data_path, IND_geno, det, cpu_cores, threshold)
}

cal_breed_pro <- function(Pedigree) {
    .Call(`_cBar2_cal_breed_pro`, Pedigree)
}

